# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jaehyeon Lee
description: Welcome to my blog!
baseurl: ""
url: "https://monkcat.github.io"
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: ewogus125@dgist.ac.mr

  follow:
    - #type: twitter
      #name: Twitter
      #link: http://twitter.com/YourTwitterUsername
      #username: "@YourTwitterUsername"
    - #type: linkedin
      #name: LinkedIn
      #link: http://linkedin.com/in/YourLinkedInUsername
    - type: github
      name: GitHub
      link: http://github.com/monkcat
    - #type: blog
      #name: Blog
      #link: https://blog.naver.com/ewogus125


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
